### ISSUE TITLE
error	[ Adapter V:3.3.2 createObjects ] Error creating all states: TypeError: Cannot read property 'length' of undefined[Bug]: 

### ISSUE THREAD

**Issue by RoboCop0815** [iobroker-community-adapters/ioBroker.tankerkoenig#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<html><body>

tankerkoenig.0 | 2023-01-02 06:39:33.749 | error | [ Adapter V:3.3.2 createObjects ] Error creating all states: TypeError: Cannot read property 'length' of undefined
-- | -- | -- | --

</body>
</html>

### Adapter version

3,3,2

### Environment

```markdown
- Node:
- npm:
- JS-Controller:
- Operating system:
Plattform
    linux
Betriebssystem
    linux
Architektur
    x64
CPUs
    8
Geschwindigkeit
    3392 MHz
Modell
    Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
RAM
    3.85 GB
System-Betriebszeit
    224 T. 10:15:01
Node.js
    v14.19.3 (Es gibt eine neuere Version: v14.21.2 - Empfohlene Version v16.19.0)
time
    1672638333485
timeOffset
    -60
Anzahl der Adapter
    450
NPM
    6.14.17
```

### What browsers are you seeing the problem on?

Firefox

**Comment by xXBJXx** [comment]
From which version did you make the update?
Please go to the UI and then edit, copy the stadium ID again so that the address is entered in the config, then add and save.
![image](https://user-images.githubusercontent.com/32600934/210220053-4c979da1-0378-4a5b-9ac8-ad2b67471d99.png)
![image](https://user-images.githubusercontent.com/32600934/210220068-fa05b947-6a9b-471d-887e-3b4e894bb12f.png)

After the reboot the message should not come anymore, please report if the message still comes.

**Comment by RoboCop0815** [comment]
from 3.2.3 or 3.2.4 at 3.3.2

**Comment by xXBJXx** [comment]
then please follow the steps I have written above
