### ISSUE TITLE
resetValues should not set the value to 0

### ISSUE THREAD

**Issue by klein0r** [iobroker-community-adapters/ioBroker.tankerkoenig#79]
When resetting states, there are better ways to reset the value

- use ``deleteState`` to remove the state or
- use the ``state.q`` flag to inform other adapters that this is not a "valid value"

See https://github.com/iobroker-community-adapters/ioBroker.statistics/issues/128

**Comment by xXBJXx** [comment]
I have now implemented it so that when the gas station is closed, the old value from the ioBroker remains and the state quality is set to ( 0x40 ⇒ Substitute value from device ). The same happens if for some reason no price is available at the gas station.
My PR here still needs to be merged for this, of course. 😃
